I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 31, in script call
    call scene3_sleep
  File "game/script.rpy", line 66, in script
    henry 'ААААААААААААААААА'
Exception: Sayer 'henry' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 31, in script call
    call scene3_sleep
  File "game/script.rpy", line 66, in script
    henry 'ААААААААААААААААА'
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'henry' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
IT princess_name_game 1.0
Sun Nov 26 18:18:41 2023
