I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 59, in script call
    call start_female # Женская ветвь
  File "game/script.rpy", line 92, in script
    if not the_end:
  File "game/script.rpy", line 92, in <module>
    if not the_end:
NameError: name 'the_end' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 59, in script call
    call start_female # Женская ветвь
  File "game/script.rpy", line 92, in script
    if not the_end:
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 92, in <module>
    if not the_end:
NameError: name 'the_end' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
IT princess_name_game 3.0
Sat Dec 23 20:47:13 2023
