I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 37, in script call
    call scene5_forest from _call_scene5_forest # Встреча с дракончиком
  File "game/script.rpy", line 37, in script call
    call scene5_forest from _call_scene5_forest # Встреча с дракончиком
ScriptError: could not find label 'scene5_forest'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 37, in script call
    call scene5_forest from _call_scene5_forest # Встреча с дракончиком
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 1725, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 37, in script call
    call scene5_forest from _call_scene5_forest # Встреча с дракончиком
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'scene5_forest'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
IT princess_name_game 1.0
Sun Nov 26 23:04:14 2023
