I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 70, in script call
    call scene9_gnoms from _call_scene9_gnoms # Встреча с гномами
  File "game/script.rpy", line 537, in script
    play siund gasp
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
Exception: Audio channel 'siund' is unknown.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 70, in script call
    call scene9_gnoms from _call_scene9_gnoms # Встреча с гномами
  File "game/script.rpy", line 537, in script
    play siund gasp
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 2259, in execute
    self.call("execute")
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\audio\music.py", line 103, in play
    c = get_channel(channel)
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\audio\audio.py", line 947, in get_channel
    raise Exception("Audio channel %r is unknown." % name)
Exception: Audio channel 'siund' is unknown.

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
IT princess_name_game 3.0
Sat Dec 16 23:39:43 2023
